# Iris Classification with Keras

#### Import Library and Load Dataset.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [93]:
df = pd.read_csv('iris.csv')

In [94]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [95]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
X = df.drop(['species'],axis=1).values

#### Generate dummies label to generate species columns as trained label

In [105]:
y = pd.get_dummies(df['species']).values

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

#### 4 Columns 120 Rows Data.

In [47]:
X_train.shape

(120, 4)

In [101]:
y.shape

(150, 3)

As this neural network model classifies multiple label it has 3 dimensional shape (Categorical)

#### Scale Dataset since neural networks require scaling numerical dataset to fast convergence

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(X_train)

MinMaxScaler()

#### We only fit on train data, to avoid prior asumption.

In [12]:
scaled_x = scaler.transform(X_train)

In [13]:
scaled_xx = scaler.transform(X_test)

#### Initiate Keras Models

In [14]:
from keras.models import Sequential

In [15]:
from keras.layers import Dense

#### Model Description

In [102]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [103]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_26 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_27 (Dense)             (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [114]:
model.fit(x=scaled_x,y=y_train,epochs=600)

Epoch 1/600
120/120 [==============================] - 0s 919us/step - loss: 0.0496 - accuracy: 0.9833
Epoch 2/600
120/120 [==============================] - 0s 259us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 3/600
120/120 [==============================] - 0s 238us/step - loss: 0.0488 - accuracy: 0.9833
Epoch 4/600
120/120 [==============================] - 0s 288us/step - loss: 0.0488 - accuracy: 0.9833
Epoch 5/600
120/120 [==============================] - 0s 234us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 6/600
120/120 [==============================] - 0s 238us/step - loss: 0.0493 - accuracy: 0.9833
Epoch 7/600
120/120 [==============================] - 0s 246us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 8/600
120/120 [==============================] - 0s 267us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 9/600
120/120 [==============================] - 0s 267us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 10/600
120/120 [==============================] - 0s 258us/step - l

120/120 [==============================] - 0s 250us/step - loss: 0.0493 - accuracy: 0.9833
Epoch 80/600
120/120 [==============================] - 0s 254us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 81/600
120/120 [==============================] - 0s 242us/step - loss: 0.0487 - accuracy: 0.9833
Epoch 82/600
120/120 [==============================] - 0s 229us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 83/600
120/120 [==============================] - 0s 229us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 84/600
120/120 [==============================] - 0s 238us/step - loss: 0.0487 - accuracy: 0.9833
Epoch 85/600
120/120 [==============================] - 0s 229us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 86/600
120/120 [==============================] - 0s 229us/step - loss: 0.0491 - accuracy: 0.9833
Epoch 87/600
120/120 [==============================] - 0s 225us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 88/600
120/120 [==============================] - 0s 342us/step - loss:

120/120 [==============================] - 0s 238us/step - loss: 0.0488 - accuracy: 0.9833
Epoch 158/600
120/120 [==============================] - 0s 246us/step - loss: 0.0489 - accuracy: 0.9833
Epoch 159/600
120/120 [==============================] - 0s 246us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 160/600
120/120 [==============================] - 0s 233us/step - loss: 0.0487 - accuracy: 0.9833
Epoch 161/600
120/120 [==============================] - 0s 250us/step - loss: 0.0488 - accuracy: 0.9833
Epoch 162/600
120/120 [==============================] - 0s 267us/step - loss: 0.0488 - accuracy: 0.9833
Epoch 163/600
120/120 [==============================] - 0s 225us/step - loss: 0.0492 - accuracy: 0.9833
Epoch 164/600
120/120 [==============================] - 0s 245us/step - loss: 0.0485 - accuracy: 0.9833
Epoch 165/600
120/120 [==============================] - 0s 225us/step - loss: 0.0491 - accuracy: 0.9833
Epoch 166/600
120/120 [==============================] - 0s 208us/ste

120/120 [==============================] - 0s 271us/step - loss: 0.0491 - accuracy: 0.9833
Epoch 236/600
120/120 [==============================] - 0s 242us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 237/600
120/120 [==============================] - 0s 246us/step - loss: 0.0487 - accuracy: 0.9833
Epoch 238/600
120/120 [==============================] - 0s 246us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 239/600
120/120 [==============================] - 0s 834us/step - loss: 0.0485 - accuracy: 0.9833
Epoch 240/600
120/120 [==============================] - 0s 367us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 241/600
120/120 [==============================] - 0s 242us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 242/600
120/120 [==============================] - 0s 241us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 243/600
120/120 [==============================] - 0s 212us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 244/600
120/120 [==============================] - 0s 229us/ste

120/120 [==============================] - 0s 246us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 313/600
120/120 [==============================] - 0s 225us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 314/600
120/120 [==============================] - 0s 225us/step - loss: 0.0485 - accuracy: 0.9833
Epoch 315/600
120/120 [==============================] - 0s 250us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 316/600
120/120 [==============================] - 0s 223us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 317/600
120/120 [==============================] - 0s 240us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 318/600
120/120 [==============================] - 0s 217us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 319/600
120/120 [==============================] - 0s 213us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 320/600
120/120 [==============================] - 0s 215us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 321/600
120/120 [==============================] - 0s 221us/ste

120/120 [==============================] - 0s 225us/step - loss: 0.0481 - accuracy: 0.9833
Epoch 391/600
120/120 [==============================] - 0s 225us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 392/600
120/120 [==============================] - 0s 234us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 393/600
120/120 [==============================] - 0s 241us/step - loss: 0.0481 - accuracy: 0.9833
Epoch 394/600
120/120 [==============================] - 0s 250us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 395/600
120/120 [==============================] - 0s 246us/step - loss: 0.0485 - accuracy: 0.9833
Epoch 396/600
120/120 [==============================] - 0s 242us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 397/600
120/120 [==============================] - 0s 242us/step - loss: 0.0484 - accuracy: 0.9833
Epoch 398/600
120/120 [==============================] - 0s 254us/step - loss: 0.0481 - accuracy: 0.9833
Epoch 399/600
120/120 [==============================] - 0s 250us/ste

120/120 [==============================] - 0s 213us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 468/600
120/120 [==============================] - 0s 192us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 469/600
120/120 [==============================] - 0s 196us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 470/600
120/120 [==============================] - 0s 367us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 471/600
120/120 [==============================] - 0s 242us/step - loss: 0.0490 - accuracy: 0.9833
Epoch 472/600
120/120 [==============================] - 0s 198us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 473/600
120/120 [==============================] - 0s 188us/step - loss: 0.0480 - accuracy: 0.9833
Epoch 474/600
120/120 [==============================] - 0s 218us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 475/600
120/120 [==============================] - 0s 208us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 476/600
120/120 [==============================] - 0s 263us/ste

120/120 [==============================] - 0s 259us/step - loss: 0.0481 - accuracy: 0.9833
Epoch 545/600
120/120 [==============================] - 0s 242us/step - loss: 0.0479 - accuracy: 0.9833
Epoch 546/600
120/120 [==============================] - 0s 250us/step - loss: 0.0478 - accuracy: 0.9833
Epoch 547/600
120/120 [==============================] - 0s 217us/step - loss: 0.0486 - accuracy: 0.9833
Epoch 548/600
120/120 [==============================] - 0s 221us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 549/600
120/120 [==============================] - 0s 225us/step - loss: 0.0479 - accuracy: 0.9833
Epoch 550/600
120/120 [==============================] - 0s 217us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 551/600
120/120 [==============================] - 0s 201us/step - loss: 0.0483 - accuracy: 0.9833
Epoch 552/600
120/120 [==============================] - 0s 200us/step - loss: 0.0482 - accuracy: 0.9833
Epoch 553/600
120/120 [==============================] - 0s 192us/ste

#### Report Probability of each classes

In [113]:
model.predict(scaled_xx)

array([[9.99999642e-01, 7.62788162e-08, 2.81541674e-07],
       [9.99992728e-01, 2.96626422e-06, 4.33281821e-06],
       [9.99352992e-01, 4.59316245e-04, 1.87590020e-04],
       [6.22785194e-07, 5.07488370e-01, 4.92511034e-01],
       [1.21559253e-07, 9.99652028e-01, 3.47870839e-04],
       [9.82190500e-07, 3.31030674e-02, 9.66895878e-01],
       [9.90191438e-06, 4.08260226e-01, 5.91729879e-01],
       [6.70481268e-06, 9.95741844e-01, 4.25156206e-03],
       [1.66913381e-07, 1.56899658e-03, 9.98430789e-01],
       [9.99993682e-01, 2.09897371e-06, 4.11975452e-06],
       [1.13112876e-07, 3.33869248e-03, 9.96661186e-01],
       [9.99999881e-01, 1.71376069e-08, 1.00030533e-07],
       [9.99909282e-01, 5.31461192e-05, 3.75416057e-05],
       [1.19661425e-09, 7.62077107e-05, 9.99923825e-01],
       [2.63592779e-06, 2.37408474e-01, 7.62588918e-01],
       [6.15140323e-07, 9.99339283e-01, 6.60081452e-04],
       [2.06190612e-06, 9.98933613e-01, 1.06429763e-03],
       [1.71101090e-06, 9.99009

#### Predict classes directly

easiest way is using in built function directly. and predict its classes.

In [115]:
model.predict_classes(scaled_xx)

array([0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0], dtype=int64)

#### Measuring accuracy

Our validation data.

In [118]:
y_test.argmax(axis=1)

array([0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0], dtype=int64)

In [123]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [125]:
confusion_matrix(y_test.argmax(axis=1),model.predict_classes(scaled_xx))

array([[10,  0,  0],
       [ 0, 11,  1],
       [ 0,  1,  7]], dtype=int64)

In [127]:
print(classification_report(y_test.argmax(axis=1),model.predict_classes(scaled_xx)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      0.92      0.92        12
           2       0.88      0.88      0.88         8

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [128]:
accuracy_score(y_test.argmax(axis=1),model.predict_classes(scaled_xx))

0.9333333333333333